default: &default
  adapter: mysql2
  username: root
  password: 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dbtodolist

test:
  <<: *default
  database: dbtodolist

production:
  <<: *default
  database: dbtodolist
